### ISSUE TITLE
OnChange Event

### ISSUE THREAD

**Issue by ghost** [kangsheng89/PyVectorCanoe#1]
Hi kangsheng89

Thanks for share this project.
Could you add some event functions for this project.

for example:  on sysvar change

**Comment by kangsheng89** [comment]
hello welder83,
feel free to add changes also. i will take a look on it too

**Comment by ghost** [comment]
Thank you for your rapid reply!
Actually, I want to python can receive Variable "on change" events from CANoe (e.g.  once some sysvars change, python can receive this changing immediately). But i don't know how to add this function.
